
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}


scheduler:
  cron: ${SCHEDULER_CRON}